# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-usb}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tanaka Akira", "Perryn Fowler (0.2.1 gem packaging)"]
  s.date = %q{2010-11-14}
  s.email = %q{akr@fsij.org}
  s.extensions = ["extconf.rb"]
  s.extra_rdoc_files = [
    "ChangeLog",
     "README"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "ChangeLog",
     "README",
     "Rakefile",
     "VERSION",
     "constants.h",
     "extconf.rb",
     "lib/usb.rb",
     "sample/usb-power",
     "usb.c"
  ]
  s.homepage = %q{http://github.com/akr/ruby-usb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ruby-usb is a libusb binding library for Ruby.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

